name: GHCR: Publish image

on:
  push:
  workflow_dispatch:

env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.ref_name }}-${{ github.sha }}

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3.3.0

      - name: Build image
        run: docker build . -t ${IMAGE,,} # lowercase IMAGE

      - name: Login to ghcr.io
        run: docker login https://ghcr.io -u token --password-stdin <<< ${{ github.token }}

      - name: Publish image
        run: docker push ${IMAGE,,} # lowercase IMAGE
